name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: brpaz/hadolint-action@master

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: vietnem
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vietnem/checkov
          tags: 1.0.636, 1.0
          tag_with_ref: true
